
spring:
  application:
    name: patients-api
  datasource:
    url: jdbc:mysql://localhost:3306/imss-bienestar
    username: root
    password: Fernando13.1
 
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update